version: "3.8"
services:
  frontend:
    build: "/frontend"
    ports:
      - 8080:8080
  backend:
    build: "/backend"


    ports:
      - 8081:8081
      
    volumes:
      - working-space:/working-space
      
    environment:
      - DB_HOST=db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data:
  working-space: