version: "3.8"
services:
  frontend:
    build: "/frontend"
    ports:
      - 8080:8080
    volumes:
      #- working-space:/working-space
      - ./frontend/src:/frontend/src # directly mount code to speed up development
  backend:
    build: 
      context: ./backend
      dockerfile: DockerfileDev   
    ports:
      - 8081:8080
      - 9229:9229
    volumes:
      #- working-space:/working-space
      - ./backend/src:/backend/src # directly mount code to speed up development
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - SECRETSESSIONKEY=${SECRETSESSIONKEY}
      - DBCONNECTIONLIMIT=${DBCONNECTIONLIMIT}
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - "./databaseinit/init.sql:/docker-entrypoint-initdb.d/1.sql"
     
#volumes:
  #db-data:
  #working-space: