version: "3.8"
services:
  frontend:
    build: "/frontend"
    ports:
      - 8080:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html # directly mount build code to speed up development
  backend:
    build: 
      context: ./backend
      dockerfile: DockerfileDev   
    ports:
      - 8081:8080
      - 9229:9229
    volumes:
      #- working-space:/working-space
      - ./backend/src:/backend/src # directly mount code to speed up development
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=ammendmentmanagerdb
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - SECRETSESSIONKEY=${SECRETSESSIONKEY}
      - DBCONNECTIONLIMIT=${DBCONNECTIONLIMIT}
  db:
    build: "/database"
    ports:
      - 3306:3306
    expose:
      - 3306
    image: mysql:8
    environment:
      - MYSQL_DATABASE=ammendmentmanagerdb
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    # volumes:
    #   - db-data:/var/lib/mysql
    
# volumes:
#   db-data:
#   working-space: