version: "3.8"
services:
  backend:
    build: "/backend"
    ports:
      - 8081:8080
    volumes:
      - working-space:/working-space
    environment:
      - DB_HOST=db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data:
  working-space: