version: "3.8"
services:
  frontend:
    build: "/frontend"
    ports:
      - 8080:8080


      
  backend:
    build: "/backend"


    ports:
      - 8081:8081
      
    volumes:
      - working-space:/working-space
      
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=ammendmentmanagerdb
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - SECRETSESSIONKEY=${SECRETSESSIONKEY}
      - DBCONNECTIONLIMIT=${DBCONNECTIONLIMIT}
  db:
    build: "/database"
    ports:
      # - 3306:3306  #Doesnt need to be exposed to the web for production, can be exposed temporarily for troubleshooting or manual database editing.
    expose:
      - 3306
    image: mysql:8
    environment:
      - MYSQL_DATABASE=ammendmentmanagerdb
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data:
  working-space: